export const MOMENTUM_MAX = 100;
export const MOMENTUM_INITIAL = 24;

export const MOMENTUM_DRAIN_PER_SEC = 3.8;
export const MOMENTUM_DRAIN_OVERDRIVE_SCALE = 0.7;
export const MOMENTUM_DRAIN_HIGH_SPEED_THRESHOLD = 70;
export const MOMENTUM_DRAIN_HIGH_SPEED_SCALE = 1.55;
export const LAUNCH_RAMP_SEC = 1.55;
export const LAUNCH_FAIL_GRACE_SEC = 6.0;
export const LAUNCH_DRAIN_SCALE = 0.18;

export const HUMAN_MOMENTUM_GAIN = 1.15;
export const HUMAN_COMBO_GAIN_SCALE = 0.035;
export const CHAIN_WINDOW_SEC = 2.4;

export const OVERDRIVE_COMBO_THRESHOLD = 24;
export const OVERDRIVE_DURATION_SEC = 3.0;

export const HARD_BUILDING_IMPACT_PENALTY = 8;
export const BALL_LOST_PENALTY = 12;
export const BUILDING_DESTROY_MOMENTUM_GAIN_SMALL = 0.32;
export const BUILDING_DESTROY_MOMENTUM_GAIN_MEDIUM = 0.55;
export const BUILDING_DESTROY_MOMENTUM_GAIN_LARGE = 0.9;
export const BUILDING_DESTROY_MOMENTUM_GAIN_HUGE = 1.4;

export const SCROLL_SPEED_MIN = 30;
export const SCROLL_SPEED_ROLL = 18;
export const SCROLL_SPEED_CRUISE = 62;
export const SCROLL_SPEED_MAX = 108;
export const SCROLL_SPEED_RISE_PER_SEC = 240;
export const SCROLL_SPEED_FALL_PER_SEC = 9;
export const HUMAN_SPEED_KICK = 8;
export const BUILDING_SPEED_KICK_SMALL = 15;
export const BUILDING_SPEED_KICK_MEDIUM = 23;
export const BUILDING_SPEED_KICK_LARGE = 33;
export const BUILDING_SPEED_KICK_HUGE = 45;
export const HARD_IMPACT_SPEED_DROP = 18;
export const BALL_LOST_SPEED_DROP = 36;
export const SCROLL_MOMENTUM_ROLL_THRESHOLD = 12;
export const SCROLL_MOMENTUM_CRUISE_THRESHOLD = 30;
export const SCROLL_MOMENTUM_BOOST_THRESHOLD = 70;
export const SCROLL_MOMENTUM_REDLINE_THRESHOLD = 84;
