import * as C from './constants';
import { Renderer, writeInst, INST_F } from './renderer';
import { InputManager } from './input';
import { gameplayStart, gameplayStop } from './sdk';

type State = 'title' | 'running' | 'game_over';
type Power = 1 | 2 | 3 | 4 | 5;
type RGB = readonly [number, number, number];
type District = 'residential' | 'shopping' | 'station' | 'office' | 'industrial' | 'highrise' | 'crowd';
interface Building { id:number; kind:C.BuildingSize; x:number; y:number; w:number; h:number; hp:number; maxHp:number; score:number; humans:number; tier:Power; active:boolean; flash:number; color:RGB; }
interface Human { x:number; y:number; vx:number; vy:number; life:number; value:number; active:boolean; }
interface Particle { x:number; y:number; vx:number; vy:number; life:number; size:number; color:RGB; }
interface Ball { x:number; y:number; vx:number; vy:number; r:number; }
interface Segment { ax:number; ay:number; bx:number; by:number; hw:number; kick:number; }
interface FlipState { angle:number; target:number; angularVel:number; pressed:boolean; }

const DEG = Math.PI / 180;
const MOMENTUM_MAX = 100, MOMENTUM_INITIAL = 35, MOMENTUM_DRAIN = 4.2, MOMENTUM_DRAIN_OD = 0.45;
const HUMAN_GAIN = 1.05, COMBO_GAIN_SCALE = 0.035, LOW_MOMENTUM = 18, CRIT_MOMENTUM = 10, LOW_GRACE = 3.0;
const HARD_HIT_PENALTY = 8, BALL_LOST_PENALTY = 20, OD_COMBO = 24, OD_TIME = 3.0, HUMAN_BURST_SCALE = 0.28;
const CHUNK_H = 240, FIELD_W = C.CANVAS_WIDTH, FIELD_H = C.CANVAS_HEIGHT, LEFT = C.WORLD_MIN_X, RIGHT = C.WORLD_MAX_X;
const BUF = new Float32Array(60000 * INST_F);

const COLORS: Partial<Record<C.BuildingSize, RGB>> = {
  house:[.72,.42,.30], townhouse:[.78,.55,.36], garage:[.46,.46,.44], shop:[.42,.62,.82], convenience:[.36,.78,.48],
  ramen:[.84,.32,.22], izakaya:[.74,.35,.24], apartment:[.48,.58,.70], supermarket:[.62,.82,.50], train_station:[.86,.74,.45],
  office:[.45,.70,.90], business_hotel:[.78,.82,.90], apartment_tall:[.54,.66,.80], warehouse:[.48,.47,.42], factory_stack:[.56,.48,.42],
  gas_station:[.90,.78,.22], tower:[.40,.72,.92], skyscraper:[.34,.64,.88], department_store:[.92,.75,.42], stadium:[.70,.64,.54], castle:[.96,.90,.92],
};
const DISTRICTS: ReadonlyArray<{kind:District; buildings:C.BuildingSize[]; density:number; humans:number}> = [
  {kind:'residential', buildings:['house','house','townhouse','garage','convenience'], density:9, humans:6},
  {kind:'shopping', buildings:['shop','ramen','izakaya','convenience','supermarket','apartment'], density:10, humans:10},
  {kind:'station', buildings:['train_station','shop','convenience','apartment','ramen'], density:7, humans:18},
  {kind:'office', buildings:['office','business_hotel','apartment_tall','shop','bank'], density:8, humans:10},
  {kind:'industrial', buildings:['warehouse','factory_stack','gas_station','garage','shop'], density:7, humans:5},
  {kind:'highrise', buildings:['tower','skyscraper','office','department_store','apartment_tall'], density:6, humans:10},
  {kind:'crowd', buildings:['stadium','train_station','department_store','shop'], density:5, humans:28},
];
const T1 = new Set<C.BuildingSize>(['house','townhouse','garage','shed','greenhouse','bungalow','duplex','shop','convenience','restaurant','cafe','bakery','bookstore','pharmacy','laundromat','florist','ramen','izakaya','snack','yatai','kominka','chaya','kura','dojo','wagashi','kimono_shop','sushi_ya']);
const T2 = new Set<C.BuildingSize>(['apartment','parking','supermarket','karaoke','pachinko','game_center','bank','library','museum','fire_station','police_station','movie_theater','shrine','temple','machiya','ryokan','onsen_inn','warehouse','container_stack','bus_terminal_shelter','shotengai_arcade','fountain_pavilion','love_hotel','club','capsule_hotel']);
const T3 = new Set<C.BuildingSize>(['office','apartment_tall','city_hall','business_hotel','train_station','school','hospital','department_store','factory_stack','silo','crane_gantry','pagoda','tahoto','carousel','big_tent','gas_station']);
const T4 = new Set<C.BuildingSize>(['tower','skyscraper','clock_tower','radio_tower','ferris_wheel','roller_coaster']);
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const rand=(a:number,b:number)=>a+Math.random()*(b-a);
const randInt=(a:number,b:number)=>Math.floor(rand(a,b+1));
const pick=<T,>(a:readonly T[])=>a[Math.floor(Math.random()*a.length)];
const roman=(p:Power)=>['','I','II','III','IV','V'][p] ?? 'V';
const color=(k:C.BuildingSize):RGB=>COLORS[k] ?? [.62,.58,.50];
function tier(k:C.BuildingSize):Power{ if(T1.has(k))return 1; if(T2.has(k))return 2; if(T3.has(k))return 3; if(T4.has(k))return 4; return 5; }
function circleAabb(cx:number,cy:number,r:number,bx:number,by:number,bw:number,bh:number){ const nx=clamp(cx,bx-bw/2,bx+bw/2), ny=clamp(cy,by,by+bh), dx=cx-nx, dy=cy-ny; return dx*dx+dy*dy<=r*r; }

export class RampageGame {
  private renderer:Renderer; private input:InputManager; private state:State='title'; private last=performance.now();
  private cameraY=0; private nextChunkY=-120; private momentum=MOMENTUM_INITIAL; private lowTimer=0; private combo=0; private comboTimer=0; private maxCombo=0; private od=0; private score=0; private best=0;
  private buildings:Building[]=[]; private humans:Human[]=[]; private particles:Particle[]=[]; private ball:Ball={x:C.BALL_START_X,y:C.BALL_START_Y,vx:.5,vy:0,r:C.BALL_RADIUS}; private bid=1;
  private left:FlipState={angle:-25*DEG,target:-25*DEG,angularVel:0,pressed:false}; private right:FlipState={angle:205*DEG,target:205*DEG,angularVel:0,pressed:false};
  private title=document.getElementById('title'); private over=document.getElementById('gameover'); private scoreEl=document.getElementById('score-display'); private bestEl=document.getElementById('best-display'); private fill=document.getElementById('life-fill') as HTMLElement|null; private wrap=document.getElementById('life-wrap') as HTMLElement|null; private zone=document.getElementById('zone-display'); private dist=document.getElementById('distance-display'); private finalScore=document.getElementById('final-score'); private finalBest=document.getElementById('final-best'); private finalStats=document.getElementById('final-stats'); private finalRecord=document.getElementById('final-record');
  constructor(canvas:HTMLCanvasElement){ this.renderer=new Renderer(canvas); this.input=new InputManager(canvas); this.reset(); this.setupDom(); this.loop(performance.now()); }
  private setupDom(){ this.title?.classList.add('show'); const h=this.title?.querySelector('h1'); if(h)h.innerHTML='RAMPAGE<br>PINBALL'; const sub=document.getElementById('title-sub'); if(sub)sub.innerHTML='CRUSH THE CITY.<br>STOMP FOR SPEED.'; const start=(e?:Event)=>{e?.preventDefault(); if(this.state==='running')return; if(this.state==='game_over')this.reset(); this.state='running'; this.title?.classList.remove('show'); this.over?.classList.remove('show'); gameplayStart(); this.last=performance.now();}; this.title?.addEventListener('click',start); this.title?.addEventListener('touchstart',start,{passive:false}); this.over?.addEventListener('click',start); this.over?.addEventListener('touchstart',start,{passive:false}); window.addEventListener('keydown',e=>{if(this.state!=='running'&&!e.ctrlKey&&!e.metaKey&&!e.altKey)start(e);}); }
  private reset(){ this.state='title'; this.cameraY=0; this.nextChunkY=-120; this.momentum=MOMENTUM_INITIAL; this.lowTimer=0; this.combo=0; this.comboTimer=0; this.maxCombo=0; this.od=0; this.score=0; this.buildings=[]; this.humans=[]; this.particles=[]; this.ball={x:-145,y:this.cameraY-110,vx:.7,vy:0,r:C.BALL_RADIUS}; this.left={angle:-25*DEG,target:-25*DEG,angularVel:0,pressed:false}; this.right={angle:205*DEG,target:205*DEG,angularVel:0,pressed:false}; while(this.nextChunkY<1700)this.spawnDistrict(this.nextChunkY); this.updateHud(); }
  private loop(now:number){ const dt=Math.min(.033,(now-this.last)/1000||0); this.last=now; if(this.state==='running')this.update(dt); this.render(); requestAnimationFrame(t=>this.loop(t)); }
  private update(dt:number){ this.updateMomentum(dt); this.updateFlippers(dt); this.cameraY+=this.scrollSpeed()*dt; while(this.nextChunkY<this.cameraY+1200)this.spawnDistrict(this.nextChunkY); this.updateBall(dt); this.updateBuildings(dt); this.updateHumans(dt); this.updateParticles(dt); this.updateCombo(dt); this.updateFailure(dt); this.cleanup(); this.updateHud(); }
  private updateMomentum(dt:number){ this.addMomentum(-(this.od>0?MOMENTUM_DRAIN*MOMENTUM_DRAIN_OD:MOMENTUM_DRAIN)*dt); this.od=Math.max(0,this.od-dt); }
  private updateFlippers(dt:number){ const step=22*dt; const upd=(f:FlipState,pressed:boolean,rest:number,active:number)=>{f.pressed=pressed; f.target=(pressed?active:rest)*DEG; const before=f.angle, d=f.target-f.angle; if(Math.abs(d)<=step)f.angle=f.target; else f.angle+=Math.sign(d)*step; f.angularVel=(f.angle-before)/Math.max(dt,1/240);}; upd(this.left,this.input.leftPressed,-25,34); upd(this.right,this.input.rightPressed,205,146); }
  private inlanes():Segment[]{ const y=this.cameraY; return [{ax:-148,ay:y-158,bx:-96,by:y-208,hw:6,kick:1.15},{ax:148,ay:y-158,bx:96,by:y-208,hw:6,kick:1.15}]; }
  private updateBall(dt:number){ const flL=this.flipper(false), flR=this.flipper(true); this.ball.vy-=C.GRAVITY*74*dt; this.ball.x+=this.ball.vx*60*dt; this.ball.y+=this.ball.vy*60*dt; this.ball.vx*=.993; this.ball.vy*=.993; if(this.ball.x<LEFT+this.ball.r){this.ball.x=LEFT+this.ball.r; this.ball.vx=Math.abs(this.ball.vx)*.72;} if(this.ball.x>RIGHT-this.ball.r){this.ball.x=RIGHT-this.ball.r; this.ball.vx=-Math.abs(this.ball.vx)*.72;} if(this.ball.y>this.cameraY+C.WORLD_MAX_Y-this.ball.r){this.ball.y=this.cameraY+C.WORLD_MAX_Y-this.ball.r; this.ball.vy=-Math.abs(this.ball.vy)*.62;} for(const s of this.inlanes())this.resolveSeg(s); this.resolveFlipper(flL); this.resolveFlipper(flR); this.checkBuildings(); if(this.ball.y<this.cameraY+C.FALLOFF_Y-26){this.addMomentum(-BALL_LOST_PENALTY); this.combo=0; this.comboTimer=0; this.ball={x:-145,y:this.cameraY-120,vx:.5,vy:0,r:C.BALL_RADIUS};} }
  private resolveSeg(s:Segment){ const dx=s.bx-s.ax, dy=s.by-s.ay, l=dx*dx+dy*dy, t=clamp(((this.ball.x-s.ax)*dx+(this.ball.y-s.ay)*dy)/l,0,1), px=s.ax+dx*t, py=s.ay+dy*t, ox=this.ball.x-px, oy=this.ball.y-py, dist=Math.hypot(ox,oy)||1, min=this.ball.r+s.hw; if(dist>=min)return; const nx=ox/dist, ny=oy/dist; this.ball.x=px+nx*min; this.ball.y=py+ny*min; const vn=this.ball.vx*nx+this.ball.vy*ny; if(vn<0){this.ball.vx-=1.28*vn*nx; this.ball.vy-=1.28*vn*ny;} this.ball.vy+=s.kick; this.ball.vx+=(px<0?.28:-.28)*s.kick; }
  private flipper(right:boolean){ const f=right?this.right:this.left, px=right?C.FLIPPER_PIVOT_X:-C.FLIPPER_PIVOT_X, py=this.cameraY+C.FLIPPER_PIVOT_Y; return {ax:px,ay:py,bx:px+Math.cos(f.angle)*C.FLIPPER_W,by:py+Math.sin(f.angle)*C.FLIPPER_W,state:f,right}; }
  private resolveFlipper(f:ReturnType<RampageGame['flipper']>){ const dx=f.bx-f.ax, dy=f.by-f.ay, l=dx*dx+dy*dy, t=clamp(((this.ball.x-f.ax)*dx+(this.ball.y-f.ay)*dy)/l,0,1), px=f.ax+dx*t, py=f.ay+dy*t, ox=this.ball.x-px, oy=this.ball.y-py, dist=Math.hypot(ox,oy)||1, min=this.ball.r+5; if(dist>=min)return; const nx=ox/dist, ny=oy/dist; this.ball.x=px+nx*min; this.ball.y=py+ny*min; const rising=f.right?f.state.angularVel<-.2:f.state.angularVel>.2, swing=clamp(Math.abs(f.state.angularVel)/16,0,1.35), k=rising?8+swing*17:4; this.ball.vx+=nx*k+(f.right?-2.4:2.4)+(rising?(f.right?-4.5:4.5):0); this.ball.vy+=Math.max(3,ny*k)+(rising?12+swing*9:2); }
  private checkBuildings(){ for(const b of this.buildings){ if(!b.active||b.y+b.h<this.cameraY+C.WORLD_MIN_Y-80||b.y>this.cameraY+C.WORLD_MAX_Y+160||!circleAabb(this.ball.x,this.ball.y,this.ball.r,b.x,b.y,b.w,b.h))continue; const p=this.power(); if(p<b.tier){this.addMomentum(-(HARD_HIT_PENALTY+(b.tier-p)*4)); this.combo=0; this.comboTimer=0; this.bounce(b,.65); this.popup(b.x,b.y+b.h,`NEED POWER ${roman(b.tier)}`); b.flash=.1; return;} b.hp-=1+Math.max(0,p-b.tier); b.flash=.08; this.bounce(b,p>b.tier?.35:.55); if(b.hp<=0)this.destroy(b); return;} }
  private bounce(b:Building,r:number){ const dx=this.ball.x-b.x, dy=this.ball.y-(b.y+b.h/2); if(Math.abs(dx)>Math.abs(dy))this.ball.vx=Math.sign(dx||1)*Math.max(4,Math.abs(this.ball.vx))*r; else this.ball.vy=Math.sign(dy||1)*Math.max(4,Math.abs(this.ball.vy))*r; }
  private destroy(b:Building){ b.active=false; this.score+=Math.floor(b.score*(1+this.combo*.08)*(1+this.momentum/180)); this.addMomentum(b.tier*.7); this.comboTimer=Math.max(this.comboTimer,1.1); this.spawnHumans(b); for(let i=0;i<16+b.tier*8;i++)this.particles.push({x:b.x+rand(-b.w/2,b.w/2),y:b.y+rand(0,b.h),vx:rand(-70,70),vy:rand(-20,90),life:rand(.35,.75),size:rand(2,5),color:b.color}); }
  private spawnHumans(b:Building){ const count=clamp(Math.floor(b.humans*HUMAN_BURST_SCALE),2,55); for(let i=0;i<count;i++){ const a=rand(0,Math.PI*2), sp=rand(22,68)+b.tier*7, away=Math.sign((b.x-this.ball.x)||rand(-1,1)); this.humans.push({x:b.x+Math.cos(a)*rand(4,16),y:b.y+b.h*rand(.2,.8),vx:Math.cos(a)*sp+away*18,vy:Math.sin(a)*sp+18,life:rand(3.5,6),value:1+b.tier*.22,active:true}); } this.popup(b.x,b.y+b.h+10,`PANIC +${count}`); }
  private updateBuildings(dt:number){for(const b of this.buildings)b.flash=Math.max(0,b.flash-dt);} private updateHumans(dt:number){for(const h of this.humans){if(!h.active)continue; h.life-=dt; h.x+=h.vx*dt; h.y+=h.vy*dt; h.vx+=(h.x>=this.ball.x?1:-1)*10*dt; h.vy+=5*dt; if(h.x<LEFT+6||h.x>RIGHT-6)h.vx*=-.65; if(h.life<=0||h.y<this.cameraY+C.WORLD_MIN_Y-70){h.active=false;continue;} const dx=h.x-this.ball.x,dy=h.y-this.ball.y; if(dx*dx+dy*dy<=(this.ball.r+5)*(this.ball.r+5))this.crush(h);}} private crush(h:Human){h.active=false; this.combo++; this.maxCombo=Math.max(this.maxCombo,this.combo); this.comboTimer=1.35; const m=1+Math.min(this.combo,50)*COMBO_GAIN_SCALE; this.addMomentum(HUMAN_GAIN*h.value*m); this.score+=Math.floor(10*m); if(this.combo>=OD_COMBO)this.od=Math.max(this.od,OD_TIME); this.particles.push({x:h.x,y:h.y,vx:0,vy:38,life:.32,size:7,color:[1,.25,.15]});}
  private updateParticles(dt:number){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy-=55*dt;p.life-=dt;} this.particles=this.particles.filter(p=>p.life>0);} private updateCombo(dt:number){if(this.comboTimer>0)this.comboTimer-=dt;if(this.comboTimer<=0)this.combo=0;} private updateFailure(dt:number){if(this.momentum<=CRIT_MOMENTUM)this.lowTimer+=dt;else this.lowTimer=0;if(this.lowTimer>=LOW_GRACE)this.gameOver();} private gameOver(){this.state='game_over'; gameplayStop(); this.best=Math.max(this.best,this.score); if(this.finalScore)this.finalScore.textContent=`SCORE ${this.score.toLocaleString()}`; if(this.finalBest)this.finalBest.textContent=`${Math.floor(this.cameraY/10).toLocaleString()} m | MAX COMBO ${this.maxCombo}`; if(this.finalStats)this.finalStats.textContent=`POWER ${roman(this.power())} | MOMENTUM ${Math.round(this.momentum)}%`; if(this.finalRecord)this.finalRecord.textContent=`BEST ${this.best.toLocaleString()}`; this.over?.classList.add('show');}
  private cleanup(){const bottom=this.cameraY+C.WORLD_MIN_Y-240; this.buildings=this.buildings.filter(b=>b.active||b.y+b.h>bottom); this.humans=this.humans.filter(h=>h.active&&h.y>bottom);} private addMomentum(v:number){this.momentum=clamp(this.momentum+v,0,MOMENTUM_MAX);} private power():Power{if(this.od>0)return 5;if(this.momentum>=95)return 5;if(this.momentum>=75)return 4;if(this.momentum>=50)return 3;if(this.momentum>=25)return 2;return 1;} private scrollSpeed(){const t=clamp(this.momentum/MOMENTUM_MAX,0,1); return 22+(96-22)*t;}
  private spawnDistrict(y:number){const d=this.pickDistrict(), lanes=[-138,-84,-30,30,84,138]; for(let i=0;i<d.density;i++){const kind=pick(d.buildings), def=C.BUILDING_DEFS[kind]; this.buildings.push({id:this.bid++,kind,x:pick(lanes)+rand(-8,8),y:y+rand(18,CHUNK_H-26),w:def.w,h:def.h,hp:def.hp,maxHp:def.hp,score:def.score,humans:randInt(def.humanMin,def.humanMax)+d.humans,tier:tier(kind),active:true,flash:0,color:color(kind)});} const ambient=d.kind==='residential'?5:Math.floor(d.humans*.35); for(let i=0;i<ambient;i++)this.humans.push({x:rand(LEFT+18,RIGHT-18),y:y+rand(12,CHUNK_H-10),vx:rand(-22,22),vy:rand(-8,18),life:rand(5,9),value:.65,active:true}); this.nextChunkY=y+CHUNK_H;}
  private pickDistrict(){if(this.nextChunkY<480)return DISTRICTS[Math.random()<.65?0:1]; if(this.momentum<22&&Math.random()<.55)return DISTRICTS[0]; if(this.combo>=12&&Math.random()<.25)return DISTRICTS[6]; if(this.momentum>70&&Math.random()<.35)return pick([DISTRICTS[2],DISTRICTS[4],DISTRICTS[5],DISTRICTS[6]]); return pick(DISTRICTS);} private popup(x:number,y:number,text:string){const p=document.createElement('div'); p.className='world-popup score'; p.textContent=text; p.style.left=`${x+FIELD_W/2}px`; p.style.top=`${FIELD_H/2-(y-this.cameraY)}px`; document.getElementById('popup-layer')?.appendChild(p); setTimeout(()=>p.remove(),850);}
  private updateHud(){const pct=clamp(this.momentum,0,100); if(this.fill)this.fill.style.width=`${pct}%`; if(this.wrap){this.wrap.classList.toggle('low',this.momentum<=LOW_MOMENTUM&&this.momentum>CRIT_MOMENTUM); this.wrap.classList.toggle('crit',this.momentum<=CRIT_MOMENTUM);} const p=this.power(); if(this.zone)this.zone.textContent=`${this.od>0?'OVERDRIVE':`POWER ${roman(p)}`} / CHAIN ${this.combo}`; if(this.dist)this.dist.textContent=`${Math.max(0,Math.floor(this.cameraY/10)).toLocaleString()} m`; if(this.scoreEl)this.scoreEl.textContent=`SCORE ${this.score.toLocaleString()}`; if(this.bestEl){if(this.best>0){this.bestEl.textContent=`BEST ${this.best.toLocaleString()}`;this.bestEl.classList.remove('hidden');}else this.bestEl.classList.add('hidden');}}
  private render(){const p=this.power(); this.renderer.updateProjection(this.cameraY); const t=clamp(this.momentum/100,0,1); this.renderer.drawBackground(.10+t*.10,.12+t*.05,.18,.05,.04,.05); let n=0; n=this.drawRoads(n); n=this.drawBuildings(n,p); n=this.drawHumans(n); n=this.drawParticles(n); n=this.drawInlanes(n); n=this.drawFlippers(n); n=this.drawBall(n); this.renderer.drawInstances(BUF,n);} private drawRoads(n:number){const start=Math.floor((this.cameraY+C.WORLD_MIN_Y)/CHUNK_H)*CHUNK_H; for(let y=start;y<this.cameraY+C.WORLD_MAX_Y+CHUNK_H;y+=CHUNK_H){writeInst(BUF,n++,0,y,360,8,.24,.23,.23,1);writeInst(BUF,n++,0,y+CHUNK_H*.48,360,12,.20,.20,.21,1);writeInst(BUF,n++,0,y+CHUNK_H*.78,360,6,.22,.21,.20,1);writeInst(BUF,n++,0,y+CHUNK_H*.24,8,CHUNK_H*.5,.18,.18,.19,1);}return n;}
  private drawBuildings(n:number,power:Power){for(const b of this.buildings){if(!b.active||b.y+b.h<this.cameraY+C.WORLD_MIN_Y-80||b.y>this.cameraY+C.WORLD_MAX_Y+120)continue; const col=b.flash>0?[1,1,1] as const:b.color, can=power>=b.tier; writeInst(BUF,n++,b.x,b.y+b.h/2,b.w,b.h,col[0],col[1],col[2],1); writeInst(BUF,n++,b.x,b.y+b.h-5,Math.max(4,b.w-5),3,can?1:.35,can?.82:.10,can?.12:.10,1); if(b.maxHp>1)for(let i=0;i<Math.max(0,b.hp);i++)writeInst(BUF,n++,b.x-b.w/2+5+i*5,b.y+b.h+5,3,3,1,.25,.15,1);} return n;} private drawHumans(n:number){for(const h of this.humans)if(h.active&&h.y>=this.cameraY+C.WORLD_MIN_Y-20&&h.y<=this.cameraY+C.WORLD_MAX_Y+20)writeInst(BUF,n++,h.x,h.y,C.HUMAN_W,C.HUMAN_H,1,.82,.52,1);return n;} private drawParticles(n:number){for(const p of this.particles)if(p.y>=this.cameraY+C.WORLD_MIN_Y-20&&p.y<=this.cameraY+C.WORLD_MAX_Y+20)writeInst(BUF,n++,p.x,p.y,p.size,p.size,p.color[0],p.color[1],p.color[2],clamp(p.life*2,0,1));return n;}
  private drawInlanes(n:number){for(const s of this.inlanes()){const cx=(s.ax+s.bx)/2,cy=(s.ay+s.by)/2,len=Math.hypot(s.bx-s.ax,s.by-s.ay),a=Math.atan2(s.by-s.ay,s.bx-s.ax);writeInst(BUF,n++,cx,cy,len,s.hw*2,.88,.58,.18,1,a);writeInst(BUF,n++,cx,cy+2,len*.84,2,1,.86,.28,1,a);}return n;} private drawFlippers(n:number){for(const f of [this.flipper(false),this.flipper(true)]){const cx=(f.ax+f.bx)/2,cy=(f.ay+f.by)/2,a=Math.atan2(f.by-f.ay,f.bx-f.ax);writeInst(BUF,n++,cx,cy,C.FLIPPER_W,8,1,.82,.12,1,a);}return n;} private drawBall(n:number){const hot=this.od>0;writeInst(BUF,n++,this.ball.x,this.ball.y,this.ball.r*2,this.ball.r*2,1,hot?.88:.22,hot?.18:.10,1,0,1);writeInst(BUF,n++,this.ball.x-5,this.ball.y+5,6,6,1,.75,.55,1,0,1);return n;}
}
